// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0pdPFuHHwO47KbvmJkazDm8EJSGl3fcs',
    appId: '1:686806436342:web:859076a3f5a4bca7975fd7',
    messagingSenderId: '686806436342',
    projectId: 'rental-1edce',
    authDomain: 'rental-1edce.firebaseapp.com',
    databaseURL: 'https://rental-1edce-default-rtdb.firebaseio.com',
    storageBucket: 'rental-1edce.firebasestorage.app',
    measurementId: 'G-C3YP038D2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8AELoHQdv_9t8uvsNnP7e8mLDgLf7g54',
    appId: '1:686806436342:android:ebf92262a087ced4975fd7',
    messagingSenderId: '686806436342',
    projectId: 'rental-1edce',
    databaseURL: 'https://rental-1edce-default-rtdb.firebaseio.com',
    storageBucket: 'rental-1edce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8M3qgP0ickjrcdHM-nLjO7ur9ZdxZPFA',
    appId: '1:686806436342:ios:e33d5ffe5b06b587975fd7',
    messagingSenderId: '686806436342',
    projectId: 'rental-1edce',
    databaseURL: 'https://rental-1edce-default-rtdb.firebaseio.com',
    storageBucket: 'rental-1edce.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8M3qgP0ickjrcdHM-nLjO7ur9ZdxZPFA',
    appId: '1:686806436342:ios:e33d5ffe5b06b587975fd7',
    messagingSenderId: '686806436342',
    projectId: 'rental-1edce',
    databaseURL: 'https://rental-1edce-default-rtdb.firebaseio.com',
    storageBucket: 'rental-1edce.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0pdPFuHHwO47KbvmJkazDm8EJSGl3fcs',
    appId: '1:686806436342:web:036575ec61f95d3f975fd7',
    messagingSenderId: '686806436342',
    projectId: 'rental-1edce',
    authDomain: 'rental-1edce.firebaseapp.com',
    databaseURL: 'https://rental-1edce-default-rtdb.firebaseio.com',
    storageBucket: 'rental-1edce.firebasestorage.app',
    measurementId: 'G-4CNSKD78Q3',
  );

}